// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13/06/2024, 09:46:49
const configMerger = require("/home/miguel/Downloads/zombie-front/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/miguel/Downloads/zombie-front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/miguel/Downloads/zombie-front/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/miguel/Downloads/zombie-front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/miguel/Downloads/zombie-front/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/miguel/Downloads/zombie-front/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/miguel/Downloads/zombie-front/plugins/**/*.{js,ts,mjs}","/home/miguel/Downloads/zombie-front/composables/**/*.{js,ts,mjs}","/home/miguel/Downloads/zombie-front/utils/**/*.{js,ts,mjs}","/home/miguel/Downloads/zombie-front/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/miguel/Downloads/zombie-front/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/miguel/Downloads/zombie-front/app.config.{js,ts,mjs}"] }));

module.exports = config
